### ISSUE TITLE
error when trying to compile on manjaro linux (kernel 4.14)

### ISSUE THREAD

**Issue by sgitkene** [EiNSTeiN-/mwifiex#2]
First, thanks for making this patch and publishing it, the mwifiex driver is really wonky with this _Marvellous_ wifi chip.

```sgit@sgit-surface ~/mwifiex> make
make -C /lib/modules/4.14.12-1-MANJARO/build SUBDIRS=/home/sgit/mwifiex modules
make[1]: Entering directory '/usr/lib/modules/4.14.12-1-MANJARO/build'
  CC [M]  /home/sgit/mwifiex/main.o
/home/sgit/mwifiex/main.c: In function ‘mwifiex_close’:
/home/sgit/mwifiex/main.c:693:42: warning: passing argument 2 of ‘cfg80211_scan_done’ makes pointer from integer without a cast [-Wint-conversion]
   cfg80211_scan_done(priv->scan_request, 1);
                                          ^
In file included from ./include/net/mac80211.h:23:0,
                 from /home/sgit/mwifiex/decl.h:30,
                 from /home/sgit/mwifiex/main.h:41,
                 from /home/sgit/mwifiex/main.c:20:
./include/net/cfg80211.h:4600:6: note: expected ‘struct cfg80211_scan_info *’ but argument is of type ‘int’
 void cfg80211_scan_done(struct cfg80211_scan_request *request,
      ^~~~~~~~~~~~~~~~~~
/home/sgit/mwifiex/main.c: In function ‘mwifiex_init_priv_params’:
/home/sgit/mwifiex/main.c:1233:7: error: ‘struct net_device’ has no member named ‘destructor’; did you mean ‘priv_destructor’?
  dev->destructor = free_netdev;
       ^~~~~~~~~~
       priv_destructor
make[2]: *** [scripts/Makefile.build:315: /home/sgit/mwifiex/main.o] Error 1
make[1]: *** [Makefile:1507: _module_/home/sgit/mwifiex] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.14.12-1-MANJARO/build'
make: *** [Makefile:61: default] Error 2
```

replacing `destructor` with `priv_destructor` lead to 
```In file included from ./include/net/mac80211.h:23:0,
                 from /home/sgit/mwifiex/decl.h:30,
                 from /home/sgit/mwifiex/main.h:41,
                 from /home/sgit/mwifiex/main.c:20:
./include/net/cfg80211.h:4600:6: note: expected ‘struct cfg80211_scan_info *’ but argument is of type ‘int’
 void cfg80211_scan_done(struct cfg80211_scan_request *request,
      ^~~~~~~~~~~~~~~~~~
  CC [M]  /home/sgit/mwifiex/init.o
/home/sgit/mwifiex/init.c: In function ‘mwifiex_set_trans_start’:
/home/sgit/mwifiex/init.c:320:7: error: ‘struct net_device’ has no member named ‘trans_start’; did you mean ‘mem_start’?
  dev->trans_start = jiffies;
```
